# Generated by Django 5.0.1 on 2024-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_equipo_fotografía'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalles_programas_saludables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_id', models.IntegerField()),
                ('rutina_id', models.IntegerField()),
                ('dieta_id', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'detalles_programas_saludables',
            },
        ),
        migrations.CreateModel(
            name='ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_formal', models.CharField(max_length=80)),
                ('nombre_comun', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('video_ejemplo', models.CharField(max_length=100)),
                ('consideraciones', models.TextField()),
                ('dificultad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ejercicios',
            },
        ),
        migrations.CreateModel(
            name='programas_saludables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('usuario_id', models.IntegerField()),
                ('instructor', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estatus', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=80)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_ultima_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'programas_saludables',
            },
        ),
        migrations.CreateModel(
            name='rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('tiempo_aproximado', models.DateField()),
                ('estatus', models.CharField(max_length=50)),
                ('resultados_esperados', models.TextField()),
            ],
            options={
                'db_table': 'rutinas',
            },
        ),
        migrations.CreateModel(
            name='rutinas_ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_id', models.IntegerField()),
                ('rutina_id', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('tiempo', models.DateField()),
                ('estatus', models.BinaryField()),
            ],
            options={
                'db_table': 'rutinas_ejercicios',
            },
        ),
        migrations.CreateModel(
            name='sesiones_rutinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sesion', models.IntegerField()),
                ('id_rutina', models.IntegerField()),
                ('id_instructor', models.IntegerField()),
                ('asistencia', models.BinaryField()),
                ('fecha_sesion', models.DateTimeField()),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'sesiones_rutinas',
            },
        ),
        migrations.DeleteModel(
            name='Consumible',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='EquipoExistencia',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.DeleteModel(
            name='MiembroAdeudos',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
